on:
  push:
    branches: [ release/* ]
  workflow_dispatch:

jobs:
  pre-release:
    uses: abbgrade/PsBuildTasks/.github/workflows/pre-release-windows.yml@7e804f1bb8130bb04e7657e1c3787e7df30a4110
    with:
      module-name: PsSqlMermaid
    secrets:
      ps-gallery-key: ${{ secrets.PS_GALLERY_KEY }}
